### ISSUE TITLE
[central]: show video URLs in URLbar without reloading whole page, so people can link to them

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#25]
it was working like that before, but the whole page got reloaded.
maybe we can somhow adjust the url at top without forcing the whole site to reload.

**Comment by dnelband** [comment]
its not possible to change url without refreshing the page from within an iframe in zeronet, because the it already changes the url and adds this - "?wrapper_nonce=68cf91d72a1fdcb0df41aaf5b5a728befb3fd28cade084d3a3bf05e3aa455806" which results in an error when trying to change the state via html5 history.

also using a hash (#) is not possible because the zeronet api uses them for (#publish). 

but we can add a button which will generate a specific link, like this for example - http://127.0.0.1:43110/18SZadPsFtTEefBK5CTvRSFiBXs9TvAGEG/?c=1CRFBc4Tn8vvYdNBQCLRbuRwLZkNaHY8kzv=19.

**Comment by haschimoto** [comment]
(removed label as long as we're brainstorming, until we decide what to do and have one way or the other for testing)

**Comment by dnelband** [comment]
9o

**Comment by dnelband** [comment]
should i switch back to different url's? maybe i can make a smoother transition between the pages, so the whole page wouldnt "flicker". or alternatively we can add a "get link" button under the player for users to share.
