### ISSUE TITLE
WHAT IS THE MATTER?

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#27]
I'm cloning channel after channel and simply doesnt work.
You should test this before claiming it works yourself, you should clone A NEW CHANNEL FROM YOUR CFRB.... , THEN UPLOADING California Dreaming WEBM, then SEE IF THIS GETS SHOWN AND PLAYED ON:
https://bit.no.com:43110/18SZadPsFtTEefBK5CTvRSFiBXs9TvAGEG/

Local of course always works, so that is no testing, the real test is always if it works on bit.no.com.

**Comment by dnelband** [comment]
1 - the reason your file wasn't shared is because of the file name (it has empty spaces & capital letters which zeronet has problems with). ive downloaded from youtube, and only when i changed the name it worked, example:
https://bit.no.com:43110/18SZadPsFtTEefBK5CTvRSFiBXs9TvAGEG/?c=1MAV8f86QtU2cK7uYBhSRNTeTxS97DpyHwv=1

 when we used the upload function i renamed the file but now with the copy / paste it doesnt go throgh the same process. now that youve found this problem ill find a solution. 

2 - i test everything before marking it ready for testing for you, including going before to see if it works on bit.no.com. and as you see, all of my videos are working, so it was working for me. if something isnt working for you doesnt mean that "nothing is working". 

3 - there is no need to waste hours if something doesnt work for you. if i mark a ticket as ready for testing, test it, if it doesnt work send it back to me until its ready for testing again. 

3 - i dont understand why you need to be offensive. i work very hard on this project, theres no one that could help / almost 0 documentation online, were talking about something that is complicated and difficult to program considering the environment & expectations. you dont always answer or responed to things on time, so i move on to what i see can be done. its really unfair that you write like that, the last two days ive been working day and night and this is very discouraging to read.

**Comment by dnelband** [comment]
from what i understood from you is that we test this together. if thats not the case ill need to test it from other computers & preferably other connection to make sure, and only after that label it as ready for testing. this will off course add more time to each ticket, but if thats what you prefer and if this will help us avoid misunderstandings then ill do it. but in that case please wait until i finish the current tickets before posting new ones.
