### ISSUE TITLE
[central]: when first downloading a video fully into cache, show the word "loading" + "percentage downloaded" underneath the "spinning wheel"

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#29]
when a video has been loaded into local cache, the buffering progress bar is fine.

But when a big video is loaded the first time, it could take quite some time to load into cache.

I think its too hard to think of a way to start playing a partitially cached video from buffer, so for now lets look into if its possible to show the percentage loaded into cache while still loading, like with p2p clients like utorrent.

**Comment by dnelband** [comment]
very problematic to implement because when a video is called via ajax zeronet downloads the file if it doesnt exist on users local drive so there is no way to determine on the client-side level if a file exists in cache or not. ill write tamas about is, maybe there is a native callback for this, but theres is not in the docs.
