### ISSUE TITLE
[central]: missing still images

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#33]
currently, no video has a preview picture anymore:
![snap 2016-08-28 at 16 49 09](https://cloud.githubusercontent.com/assets/20817185/18034517/6b392ef2-6d3f-11e6-82a2-54b4b616fb55.png)

**Comment by dnelband** [comment]
now videos that had images would show, but im currently dealing with a new problem, its impossible to create an image from a video loaded via server & save via converToDataURI within an iframe. we didnt have this problem before because during the upload process the file was read by the fileReader and converted to data uri on the spot. working on a solution, but it seems to be a problem since i tried many things already and all result in the same error.
