### ISSUE TITLE
[central]: hash error/missing videorama.db

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#45]
errors of non matching hashes for videorama.db:
![snap 2016-09-13 at 16 50 02](https://cloud.githubusercontent.com/assets/20817185/18478626/36e33838-79d2-11e6-95a0-f6d84c7cccac.png)

Also data/videorama.db is among missing files:
![snap 2016-09-13 at 16 51 36](https://cloud.githubusercontent.com/assets/20817185/18478667/5c2ee89e-79d2-11e6-856b-25f4cb41313d.png)

**Comment by dnelband** [comment]
There is a conflict because some peers now have data.json's (votes,comments which are compiled to .db) which are curropted, they contain fields that are incompatible and these creates a merge error. It happend because when we switched to merger sites other data was recieved by default and then saved to file. Im working on a solution

**Comment by haschimoto** [comment]
![snap 2016-09-13 at 12 06 41](https://cloud.githubusercontent.com/assets/20817185/18469966/984178ce-79aa-11e6-87d6-7f25372abb89.png)

**Comment by haschimoto** [comment]
now videorama.db is mismatch and missing, updated first comment screenshots
