### ISSUE TITLE
[central]: BIT: some videos appear normal on Frontpage, but do not load or show any comments on video page

### ISSUE THREAD

**Issue by haschimoto** [zer0net/_ppload-videorama-tickets#65]
https://bit.no.com:43110/18SZadPsFtTEefBK5CTvRSFiBXs9TvAGEG/view.html?c=1CRFBc4Tn8vvYdNBQCLRbuRwLZkNaHY8kzv=14

**Comment by haschimoto** [comment]
not working:

https://bit.no.com:43110/18SZadPsFtTEefBK5CTvRSFiBXs9TvAGEG/view.html?c=1CRFBc4Tn8vvYdNBQCLRbuRwLZkNaHY8kzv=13

https://bit.no.com:43110/18SZadPsFtTEefBK5CTvRSFiBXs9TvAGEG/view.html?c=1CRFBc4Tn8vvYdNBQCLRbuRwLZkNaHY8kzv=16

https://bit.no.com:43110/18SZadPsFtTEefBK5CTvRSFiBXs9TvAGEG/view.html?c=1CRFBc4Tn8vvYdNBQCLRbuRwLZkNaHY8kzv=15

**Comment by haschimoto** [comment]
but this one works:
https://bit.no.com:43110/18SZadPsFtTEefBK5CTvRSFiBXs9TvAGEG/view.html?c=1CRFBc4Tn8vvYdNBQCLRbuRwLZkNaHY8kzv=7

**Comment by haschimoto** [comment]
all videos up to v=12 work, then the others above FAIL (13, 14, 15, 16)

**Comment by dnelband** [comment]
this was a very specific bug with these 4 videos on 1CRF, instead of 1CRF on the "channel" field, these 4 had "1cRF" with a small C (this occured probably because ive loaded the site with a small c & then saved the video. im not sure how this happend) which prevented their merger-site to be accessed through videorama, ive fixed it on 1CRF locally, now they load
